version: '3.8'

services:
  weten:
    build: .
    restart: always
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

    volumes:
      - ${HOME}/weten/.n8n:/home/node/.n8n
      - ${HOME}/weten/videos:/home/node/videos
      - ${HOME}/weten/audio:/home/node/audio

    ports:
      - "5678:5678"
