version: '3.8'

services:
  gen-worker:
    build: .
    container_name: gen-worker
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped