create table public.video_generations (
  id bigint generated by default as identity not null,
  "userId" uuid not null,
  status public.video_generation_status not null,
  "userPrompt" text not null,
  resolution public.video_resolution not null,
  duration smallint not null,
  "extReferenceId" text null,
  "createdAt" timestamp with time zone not null default now(),
  "updatedAt" timestamp with time zone not null default now(),
  form public.video_form not null,
  constraint video_generations_pkey primary key (id),
  constraint video_generations_userId_fkey foreign KEY ("userId") references auth.users (id)
) TABLESPACE pg_default;