create table public.videos (
  id bigint generated by default as identity not null,
  "videoGenerationId" bigint not null,
  resolution public.video_resolution not null,
  duration smallint not null,
  form public.video_form not null,
  title text null,
  description text null,
  path text not null,
  "createdAt" timestamp with time zone null default now(),
  "userId" uuid not null,
  constraint videos_pkey primary key (id),
  constraint videos_userId_fkey foreign KEY ("userId") references auth.users (id),
  constraint videos_videoGenerationId_fkey foreign KEY ("videoGenerationId") references video_generations (id)
) TABLESPACE pg_default;